-   id: insert-license
    name: Insert license in comments
    description: "Insert a short license disclaimer as a header comment in source files"
    entry: insert_license
    language: python
    types: [text]
