from __future__ import print_function
import argparse, fileinput, os, re, sys
from .utils import is_textfile

def contains_crlf(filename):
    for line in fileinput.input([filename]):
        if line.endswith('\r\n'):
            fileinput.close()
            return True
    return False

def removes_crlf(filename):
    for line in fileinput.input([filename], inplace=True, backup='.bak'):
        print(re.sub('\r$', '', line), end='')

def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument('filenames', nargs='*', help='filenames to check')
    args = parser.parse_args(argv)
    text_files = [f for f in args.filenames if is_textfile(f)]
    files_with_crlf = [f for f in text_files if contains_crlf(f)]
    return_code = 0
    for file_with_crlf in files_with_crlf:
        print('Removing CRLF end-lines in: {0}'.format(file_with_crlf))
        try:
            removes_crlf(file_with_crlf)
            os.remove(file_with_crlf + '.bak')
            return_code = 1
        # pylint: disable=broad-except
        except Exception as error:  # e.g. a UnicodeDecodeError generated by fileinput
            print('Ignoring {} that caused a {}'.format(file_with_crlf, error.__class__))
            os.remove(file_with_crlf)  # needed on Windows apparently
            os.replace(file_with_crlf + '.bak', file_with_crlf)
    if return_code:
        print('')
        print('CRLF end-lines have been successfully removed. Now aborting the commit.')
        print('You can check the changes made. Then simply "git add --update ." and re-commit')
    return return_code

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
